[package]
name = "rust-lang"
version = "0.1.0"
authors = ["chronium"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys-wrapper="0.6.1"
peg="*"
