[package]
name = "aatrt"
version = "0.1.0"
authors = ["SplittyDev <splittydev@protonmail.com>", "chronium"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
