[package]
name = "comp-be"
version = "0.0.1"
authors = ["chronium"]
edition = "2018"
license = "MIT"

[lib]
name = "comp_be"
path = "src/lib.rs"

[dependencies]
llvm-sys-wrapper = { path = "../llvm-sys-wrapper" }
tuple-combinator = "0.2.1"
parser = { path = "../parser" }
