name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: "nightly"
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 
    - name: Install dependencies
      run: |
        sudo apt-get install llvm-6.0-dev
        sudo ln -sf /usr/bin/llvm-config-6.0 /usr/bin/llvm-config
    - uses: actions/checkout@v2
    - uses: Mushus/checkout-submodule@v1.0.1
      with:
        submodulePath: llvm-sys-wrapper
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Spector tests
      run: python3 spector.py
